### ISSUE TITLE
Cannot use superlu or superlu_dist solvers

### ISSUE THREAD

**Issue by NucciTheBoss** [conda-forge/fenics-feedstock#105]
Issue: Cannot use superlu or superlu_dist solvers

I am trying to solve a problem that requires the use of superlu_dist but it does not seem to be configured with PETSc inside my environment. I see however that superlu/5.2.1 and superlu_dist/6.2.0 are installed in the current finics package (<code>$ conda install -c conda-forge fenics</code>), but they do not appear as available methods.

Here is the output:

```
>>> list_linear_solver_methods()
Solver method  |  Description
------------------------------------------------------------------------------
bicgstab      |  Biconjugate gradient stabilized method
cg               |  Conjugate gradient method
default        |  default linear solver
gmres          |  Generalized minimal residual method
minres         |  Minimal residual method
mumps          |  MUMPS (MUltifrontal Massively Parallel Sparse direct Solver)
petsc          |  PETSc built in LU solver
richardson     |  Richardson method
tfqmr          |  Transpose-free quasi-minimal residual method
umfpack        |  UMFPACK (Unsymmetric MultiFrontal sparse LU factorization)

>>> list_lu_solver_methods()
LU method  |  Description
--------------------------------------------------------------------------
default    |  default LU solver
mumps      |  MUMPS (MUltifrontal Massively Parallel Sparse direct Solver)
petsc      |  PETSc built in LU solver
umfpack    |  UMFPACK (Unsymmetric MultiFrontal sparse LU factorization)
```
Any help is appreciated!

**Comment by johannesring** [comment]
Looks like a rebuild is needed since superlu_dist was first added to the petsc package in the end of December ([pull request #77](https://github.com/conda-forge/petsc-feedstock/pull/77)), while the latest build of fenics seems to be from the beginning of December.

**Comment by jan-janssen** [comment]
This should be fixed now.
