### ISSUE TITLE
Unable to install fenics with conda install - install process terminates with error

### ISSUE THREAD

**Issue by sreedta8** [conda-forge/fenics-feedstock#112]
OS: Ubuntu 20.04 LTS on 64-bit machine

Issue: I try to install **fenics** / **libdmumps** / fenics related packages in a conda environment and it results in termination of the install process with errors

<br/>
Environment (<code># packages in environment at /home/blueskies/miniconda3/envs/fenics:
# conda --version conda 4.9.0
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py38h924ce5b_2    conda-forge
ld_impl_linux-64          2.35                 h769bd43_9    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
libgomp                   9.3.0               h5dbcf3e_17    conda-forge
libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
ncurses                   6.2                  he1b5a44_2    conda-forge
openssl                   1.1.1h               h516909a_0    conda-forge
pip                       20.2.4                     py_0    conda-forge
python                    3.8.6           h852b56e_0_cpython    conda-forge
python_abi                3.8                      1_cp38    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
setuptools                49.6.0           py38h924ce5b_2    conda-forge
sqlite                    3.33.0               h4cf870e_1    conda-forge
tk                        8.6.10               hed695b0_1    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
</code>):

<br/>
<br>
Details about  code run to install different libraries
<code>
conda install -c conda-forge fenics
conda install -c conda-forge libdmumps
conda install -c conda-forge fenics fenics-dijitso fenics-dolfin fenics-ffc fenics-fiat fenics-libdolfin fenics-ufl
</code> 

and 
<br>
system ( <code>     active environment : fenics
    active env location : /home/blueskies/miniconda3/envs/fenics
            shell level : 2
       user config file : /home/blueskies/.condarc
 populated config files : /home/blueskies/.condarc
          conda version : 4.9.0
    conda-build version : 3.20.4
         python version : 3.8.6.final.0
       virtual packages : __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/blueskies/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/blueskies/miniconda3/pkgs
                          /home/blueskies/.conda/pkgs
       envs directories : /home/blueskies/miniconda3/envs
                          /home/blueskies/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.0 requests/2.24.0 CPython/3.8.6 Linux/5.4.0-52-generic ubuntu/20.04.1 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False</code> ):

<br>
Errors generated 
<code>   (fenics) blueskies@sz-HP15-Nb:~$ conda install fenics fenics-dijitso fenics-dolfin fenics-ffc fenics-fiat fenics-libdolfin fenics-ufl
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/blueskies/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/blueskies/miniconda3/lib/python3.8/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/home/blueskies/miniconda3/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/home/blueskies/miniconda3/lib/python3.8/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/home/blueskies/miniconda3/lib/python3.8/site-packages/conda/cli/install.py", line 261, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/home/blueskies/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 114, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "/home/blueskies/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 157, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "/home/blueskies/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 262, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/home/blueskies/miniconda3/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/home/blueskies/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 425, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/home/blueskies/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 1020, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "/home/blueskies/miniconda3/lib/python3.8/site-packages/conda/core/index.py", line 276, in get_reduced_index
        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
      File "/home/blueskies/miniconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 120, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "/home/blueskies/miniconda3/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
        yield fs.pop().result()
      File "/home/blueskies/miniconda3/lib/python3.8/concurrent/futures/_base.py", line 432, in result
        return self.__get_result()
      File "/home/blueskies/miniconda3/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
        raise self._exception
      File "/home/blueskies/miniconda3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/blueskies/miniconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 112, in <lambda>
        subdir_query = lambda url: tuple(SubdirData(Channel(url), repodata_fn=repodata_fn).query(
      File "/home/blueskies/miniconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 125, in query
        self.load()
      File "/home/blueskies/miniconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 189, in load
        _internal_state = self._load()
      File "/home/blueskies/miniconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 251, in _load
        _internal_state = self._read_local_repdata(mod_etag_headers.get('_etag'),
      File "/home/blueskies/miniconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 326, in _read_local_repdata
        _internal_state = self._process_raw_repodata_str(raw_repodata_str)
      File "/home/blueskies/miniconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 364, in _process_raw_repodata_str
        json_obj = json.loads(raw_repodata_str or '{}')
      File "/home/blueskies/miniconda3/lib/python3.8/json/__init__.py", line 357, in loads
        return _default_decoder.decode(s)
      File "/home/blueskies/miniconda3/lib/python3.8/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/home/blueskies/miniconda3/lib/python3.8/json/decoder.py", line 353, in raw_decode
        obj, end = self.scan_once(s, idx)
    json.decoder.JSONDecodeError: Invalid control character at: line 85395 column 54 (char 2467927)

`$ /home/blueskies/miniconda3/bin/conda install fenics fenics-dijitso fenics-dolfin fenics-ffc fenics-fiat fenics-libdolfin fenics-ufl`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=fenics
                CONDA_EXE=/home/blueskies/miniconda3/bin/conda
             CONDA_PREFIX=/home/blueskies/miniconda3/envs/fenics
           CONDA_PREFIX_1=/home/blueskies/miniconda3
    CONDA_PROMPT_MODIFIER=(fenics)
         CONDA_PYTHON_EXE=/home/blueskies/miniconda3/bin/python
               CONDA_ROOT=/home/blueskies/miniconda3
              CONDA_SHLVL=2
           CURL_CA_BUNDLE=<not set>
                     PATH=/home/blueskies/miniconda3/bin:/home/blueskies/miniconda3/envs/fenics/bi
                          n:/home/blueskies/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/u
                          sr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
            XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
         XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1

     active environment : fenics
    active env location : /home/blueskies/miniconda3/envs/fenics
            shell level : 2
       user config file : /home/blueskies/.condarc
 populated config files : /home/blueskies/.condarc
          conda version : 4.9.0
    conda-build version : 3.20.4
         python version : 3.8.6.final.0
       virtual packages : __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/blueskies/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/blueskies/miniconda3/pkgs
                          /home/blueskies/.conda/pkgs
       envs directories : /home/blueskies/miniconda3/envs
                          /home/blueskies/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.0 requests/2.24.0 CPython/3.8.6 Linux/5.4.0-52-generic ubuntu/20.04.1 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

**An unexpected error has occurred.** Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
</code>

**Comment by jan-janssen** [comment]
This should be fixed now, otherwise feel free to open a new issue.
