### ISSUE TITLE
Problem with superlu_dist 6/7

### ISSUE THREAD

**Issue by sblauth** [conda-forge/fenics-feedstock#149]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

I am having problems installing fenics from conda-forge. The problematic package is "superlu_dist", which recently had version 7 available on conda-forge. The error was the following: 

ImportError: libsuperlu_dist.so.6: cannot open shared object file: No such file or directory

The solution to this problem was to pin the dependency of superlu_dist to <= 6.2.0, which was also done in this repo. 

However, my CI tests today failed, again due to superlu_dist. Now, however, superlust_dist = 6.2.0 was installed, but the error is:

ImportError: libsuperlu_dist.so.7: cannot open shared object file: No such file or directory

when I try to import fenics. To me, it seems like using superlu_dist >= 7.0.0 would and should be possible. 

As this occured during my CI build, you can check the logs here: https://github.com/sblauth/cashocs/runs/4247175888?check_suite_focus=true

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by jan-janssen** [comment]
Can you try to enforce `petsc=3.16.0` rather than `petsc=3.16.1` ?

**Comment by jan-janssen** [comment]
Alternatively you can use the latest build `25` with `petsc=3.16.1` and `superlu_dist>=7`. These issues are related to the missing pinning in `superlu_dist` which I try to get fixed in https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2202 and https://github.com/conda-forge/superlu_dist-feedstock/pull/35

**Comment by sblauth** [comment]
I can confirm that it works fine now with build number `25`. 
Thanks a lot for the fast reply and the other pull requests (which will hopefully resolve the problem)
