### ISSUE TITLE
Can't install fenics with mamba

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [conda-forge/fenics-feedstock#176]
Hi!

I tried to install fenics with mamba but got this weird error:

```
Traceback (most recent call last):
  File "/opt/conda/bin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/opt/conda/lib/python3.9/site-packages/mamba/mamba.py", line 53, in <module>
    import mamba.mamba_api as api
ImportError: libarchive.so.13: cannot open shared object file: No such file or directory
```

can we even use mamba to install fenics?

```
conda install -c conda-forge mamba
mamba install -c conda-forge fenics
```

**Comment by minrk** [comment]
oof, that means mamba just entirely doesn't work. It won't be related to fenics.

You can try `conda update conda mamba`, but if even that fails with import errors, you may need to reinstall conda/mamba entirely.

**Comment by RemDelaporteMathurin** [comment]
Somehow this got fixed! thanks

**Comment by minrk** [comment]
Glad you got it working!
