### ISSUE TITLE
A build without MPI support?

### ISSUE THREAD

**Issue by Aleeja137** [conda-forge/fenics-feedstock#195]
### Comment:

Is there a build compiled without MPI support? I am using this package for a project and I want to distribute some tasks among various processors using MPI, but when including MPI to the compilation script, dolfin detects it and uses it to distribute the mesh I am working with, something which I don't want it to do.  
  
From what I know, there is no way of telling dolfin not to use MPI, only by compiling it without MPI support. So, I was wondering if it is possible.  
  
Thank you in advance.

**Comment by minrk** [comment]
Sorry for not seeing this, but I don't believe dolfin can be compiled without mpi.
