### ISSUE TITLE
Warning: librdmacm.so.1: cannot open shared object file 

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [conda-forge/fenics-feedstock#211]
### Comment:

@rekomodo and I started noticing this message poping up when [running FEniCS installed with conda](https://festim-vv-report.readthedocs.io/en/latest/index.html#about-this-book):
```
[build-25072227-project-1052576-festim-vv-report:04098] mca_base_component_repository_open: unable to open mca_btl_openib: librdmacm.so.1: cannot open shared object file: No such file or directory (ignored)
```

This is our [environment file](https://github.com/festim-dev/V-V-report/blob/main/environment.yml).

Any idea?

**Comment by minrk** [comment]
This seems like a problem in opempi. There's probably an OMPI_MCA env variable to set that would fix it, or you can try explicitly selecting mpich, which has been a lot more reliable in my experience (`conda install fenics mpich`).

**Comment by RemDelaporteMathurin** [comment]
Thanks @minrk it fixed it!
