### ISSUE TITLE
Boost 1.86 needs a patch to work

### ISSUE THREAD

**Issue by sblauth** [conda-forge/fenics-feedstock#235]
Hello everyone,

I am trying to increase the maintenance of legacy FEniCS here on conda-forge. I have noticed that the rebuild for boost 1.86 at #234  does not work currently due to changes in the boost API https://github.com/conda-forge/fenics-feedstock/pull/234

At the moment, the failure seems to be related to the filesystem API, where some functions got deprecated. 

I would be happy to help out and fix this issue, but I am not so familiar with conda-forge. To me, it seems like a patch is needed that has to be included in the recipe.yml. If anyone could help and point me into the right direction how to do this, I am happy to create the patch and restore compatibility with boost.

@minrk Maybe you could help to get me started? It seems like you do a lot of work for FEniCS (and other projects) on conda-forge.

Thanks a lot.

**Comment by minrk** [comment]
Generally, the way to do a patch is to submit the patch to the [upstream repo](https://bitbucket.org/fenics-project/dolfin/src/master/), then generate the patch from there. You can either use `git format-patch` to generate the patch, or get it from the pull request itself, for example https://bitbucket.org/api/2.0/repositories/fenics-project/dolfin/pullrequests/576/patch is the patch for https://bitbucket.org/fenics-project/dolfin/pull-requests/576.

Then add the patch to `recipe/` and add it to the list of patches already in `meta.yaml`.

**Comment by sblauth** [comment]
Thanks a lot for the tips to get started. I have now created a PR to the bot's branch at https://github.com/regro-cf-autotick-bot/fenics-feedstock/pull/1 

I hope this is the right thing to do. 

Could someone take a look and run the CI on this one?

**Comment by minrk** [comment]
PRs against the bot won't work, you can make your own PR from your own fork, starting from commit in the bot's branch, though.

**Comment by sblauth** [comment]
Okay, sorry about that. Is #236 okay?

**Comment by minrk** [comment]
Yes, that looks right! Have you submitted the patch upstream? It's helpful to have a link for those.

**Comment by sblauth** [comment]
Yes, I did. It can be found here: https://bitbucket.org/fenics-project/dolfin/pull-requests/577
