### ISSUE TITLE
FEniCS should depend on specific SWIG version

### ISSUE THREAD

**Issue by johannesring** [conda-forge/fenics-feedstock#24]
FEniCS should depend on a specific SWIG version or else it will lead to problems like [this](https://fenicsproject.org/qa/12046/incompatible-swig-versions-detected-in-conda-installation).

**Comment by minrk** [comment]
Can do. How tightly to we need to pin swig? Minor version or patch?

conda already pins numpy for any package that depends on it, so that should already be covered.

**Comment by johannesring** [comment]
If you by patch mean 11 in swig version 3.0.11, then it should be patch.
