### ISSUE TITLE
unable to install in base-notebook for Jupyterhub

### ISSUE THREAD

**Issue by basnijholt** [conda-forge/fenics-feedstock#32]
In trying to setup a Jupyterhub using the provided `base-notebook` I get the following error:

```
Linking packages ...
/opt/conda/bin/.gcc-post-link.sh: line 10: lsb_release: command not found###############################################################################                                                  |  72%
/opt/conda/bin/.gcc-post-link.sh: line 49: ld: command not found
Couldn't locate crtXXX.o in default library search paths. You may not have it  at all. It is usually packaged in libc6-dev/glibc-devel packages. We will try  to locate crtXXX.o with system installed gcc...
There is no /usr/bin/gcc
*** Can't install the gcc package unless your system has crtXXX.o. ***


LinkError: Link error: Error: post-link failed for: gcc-4.8.5-7
```

reproduce with:
```
docker run -it --rm --user root jupyter/base-notebook bash
conda install --yes fenics
```

or

`env.yml`:
```
name: python3
channels:
  - conda-forge
dependencies:
  - fenics
```

`Dockerfile`:
```
FROM jupyter/base-notebook
USER root
COPY env.yml env.yml
RUN conda env update -n root -f env.yml
```

**Comment by basnijholt** [comment]
Installation is successful after installing `build-essentials`.

Shouldn't conda `gcc` be enough?

**Comment by minrk** [comment]
It looks like conda's using `ld` as part of post-link, which fires before the the gcc package is installed.  You might have a better experience being based on `minimal-notebook` or `scipy-notebook`, which do have build-essential.

**Comment by mingwandroid** [comment]
Post-link is run after installation unless you've got a bug in conda. Our `gcc` package doesn't include a linker, and at present we don't provide any linker, so you need a system binutils installed. Sorry about that.

**Comment by basnijholt** [comment]
Thanks for the explanation.

We use the `jupyter/base-notebook` to avoid the massive dependency chain.

Closing as I think this is not a bug of the build :)
