### ISSUE TITLE
FEniCS conda Mac OS X questions

### ISSUE THREAD

**Issue by sophia-wright-blue** [conda-forge/fenics-feedstock#37]
Hello, I've installed FEniCS via conda on Mac OS X Sierra, and am able to import dolfin. I have a few questions:

1. Is mshr available on the FEniCS conda package? I get the error 'no module named mshr' when I try to import mshr.

2. I also get an error 'name TimeSeries is not defined'. Is there anyway to fix this?

3. What is the best way to run a FEniCS script in Anaconda? I'm using Spyder, but am not able to obtain any plots. I don't get any errors when I try to plot, I just don't see any plots.

4. I installed Anaconda navigator (graphical installer), and it was working fine, but after installing FEniCS, (which downgraded Anaconda from 1.4 to 1.2), the Navigator does not work anymore.

Thank you

**Comment by johannesring** [comment]
1. mshr must be installed separately: https://github.com/conda-forge/mshr-feedstock/
2. `TimeSeries` requires HDF5 but DOLFIN is built without it (issue #5)
3. The conda package is using matplotlib as the default plotting backend. After calling `plot` do
    ``` python
    import matplotlib.pyplot as plt
    plt.show()
    ```
4. I don't know. Maybe you can try upgrading Anaconda again?

This is not an issue so I'm closing this. For support use the [FEniCS support](https://groups.google.com/forum/#!forum/fenics-support) mailing list.
