### ISSUE TITLE
petsc with hypre and ml

### ISSUE THREAD

**Issue by xmjiao** [conda-forge/fenics-feedstock#39]
The fenics build is missing some preconditions based on hypre and ml. It seems that it is because petsc was not built with hypre and ml, leaving some important preconditions out. The docker image supports both. Would you please enable hypre and ml for petsc? Thanks!

**Comment by garth-wells** [comment]
This is an issue for the PETSc conda package (https://github.com/conda-forge/petsc-feedstock). There are some issues around it, e.g https://github.com/conda-forge/petsc-feedstock/issues/12 and https://github.com/conda-forge/petsc-feedstock/issues/11.
