### ISSUE TITLE
include mshr?

### ISSUE THREAD

**Issue by minrk** [conda-forge/fenics-feedstock#4]
Should we be including mshr in the fenics package?

**Comment by basnijholt** [comment]
@RafalSkolasinski you might have an opinion here?

**Comment by RafalSkolasinski** [comment]
mshr is crucial for one member in our group

**Comment by garth-wells** [comment]
As a priority, I would rank it below adding PETSc and MPI support, and below adding a dev version.

**Comment by mikaem** [comment]
Agree @garth-wells. mshr could also be a package of its own...

**Comment by garth-wells** [comment]
Separate package is a good idea. mshr tends to be a bit fragile.

**Comment by minrk** [comment]
I'm fine either way. In-person dicsussion today suggested that dolfin-adjoint be its own package, so I am happy to do the same for mshr.

**Comment by RafalSkolasinski** [comment]
Are there any news about ``mshr``?

**Comment by jbweston** [comment]
FYI we have a working recipe for `mshr` [here](https://gitlab.kwant-project.org/qt/mshr-conda-recipe) It's on the [quantumtinkerer](https://anaconda.org/quantumtinkerer/mshr) channel on Anaconda.

**Comment by minrk** [comment]
@jbweston would you like to submit your mshr recipe to conda-forge/staged-recipes? I can do it, too, if you would prefer.

**Comment by jbweston** [comment]
@minrk I think you are more familiar with how to make conda-smithy compatible "feedstock" repositories, so it would be best if you do it.

**Comment by jbweston** [comment]
Also note that the tests for the recipe currently consist of "can we import mshr?" which is perhaps a somewhat less-than-foolproof test battery.

**Comment by basnijholt** [comment]
@jbweston just added https://github.com/conda-forge/staged-recipes/pull/2290 😄

**Comment by minrk** [comment]
Sorry, should have commented here. https://github.com/conda-forge/staged-recipes/pull/2159 just landed, waiting for the feedstock to finish building (https://github.com/conda-forge/mshr-feedstock). I had to do a bit of fiddling to get the mac builds to finish, but they work now.

**Comment by minrk** [comment]
mshr feedstock first build is finished.
