### ISSUE TITLE
Installing mpi4py breaks JIT.

### ISSUE THREAD

**Issue by terjekv** [conda-forge/fenics-feedstock#43]
After installing Anaconda 4.3.1 and fenics from conda-forge, everything seems to work very well. The JIT works and the tests I have pass fine. However, I have received user requests for mpi4py with the install. After mpi4py is installed, JIT fails with the following error:

`"PETSc was configured with MPICH but now appears to be compiling using a non-MPICH mpi.h"

I have attached the complete compile log. I have redone the build without mpich on the system without any change to the result. Any advice on how to proceed would be most welcome.

[compile.log.txt](https://github.com/conda-forge/fenics-feedstock/files/1005627/compile.log.txt)

`

**Comment by minrk** [comment]
How are you installing mpi4py?

**Comment by minrk** [comment]
strange, that should get mpi4py linked against mpich. What's

    conda list --show-channel-urls

?
