### ISSUE TITLE
link hdf5

### ISSUE THREAD

**Issue by minrk** [conda-forge/fenics-feedstock#5]
fenics should link hdf5, but it should be a parallel build and conda-forge only has a serial hdf5 package.

cf https://github.com/conda-forge/hdf5-feedstock/issues/51

**Comment by garth-wells** [comment]
We're working towards supporting serial HDF5 in DOLFIN.

**Comment by johannesring** [comment]
Does DOLFIN 2017.1 work with serial HDF5? In that case, we should enable this and rebuild the package.

**Comment by garth-wells** [comment]
@chrisrichardson says that DOLFIN 2017.1 works with serial HDF5.

**Comment by johannesring** [comment]
Good - I will try to add it.

**Comment by johannesring** [comment]
I can confirm that the serial HDF5 seems to be working fine with DOLFIN.

**Comment by johannesring** [comment]
Fixed in pull request #45.
