### ISSUE TITLE
Add dev version

### ISSUE THREAD

**Issue by garth-wells** [conda-forge/fenics-feedstock#6]
Would be helpful to have a dev version, since this package makes it easier to install on cloud services, which in turn will drive work on the dev version to enhance support for browser based visualisation.

**Comment by mikaem** [comment]
dev branch has been created and tests are currently running.

**Comment by mikaem** [comment]
I did a little check on the circle error (https://circleci.com/gh/conda-forge/fenics-feedstock/16) and entered the docker image after it had failed (I ran `bash ci_support/run_docker_build.sh`).  When I go to the directory of _la.so in the test that fails `/opt/conda/envs/_test/lib/python2.7/site-packages/dolfin/cpp`  and enter `import _la` in python I get `ImportError: ./_la.so: undefined symbol: _ZN6dolfin11PETScObject11petsc_errorEiSsSs`, which looks very related to the error message we get on travis for osx:
Undefined symbols for architecture x86_64:
  "dolfin::PETScObject::petsc_error(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)", referenced from:
      _wrap_PETScObject_petsc_error(_object*, _object*) in modulePYTHON_wrap.cxx.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [dolfin/swig/modules/la/_la.so] Error 1
make[1]: *** [dolfin/swig/modules/la/CMakeFiles/_la.dir/all] Error 2

Any ideas?

**Comment by garth-wells** [comment]
I know what the problem is - we need a PETSc include guard. I'll fix
shortly.

Garth

On 28 Oct 2016 15:04, "Mikael Mortensen" <notifications@github.com> wrote:
>
> I did a little check on the circle error (
https://circleci.com/gh/conda-forge/fenics-feedstock/16) and entered the
docker image after it had failed (I ran bash
ci_support/run_docker_build.sh). When I go to the directory of _la.so in
the test that fails
/opt/conda/envs/_test/lib/python2.7/site-packages/dolfin/cpp and enter
import _la in python I get ImportError: ./_la.so: undefined symbol:
_ZN6dolfin11PETScObject11petsc_errorEiSsSs, which looks very related to the
error message we get on travis for osx:
> Undefined symbols for architecture x86_64:
> "dolfin::PETScObject::petsc_error(int, std::__1::basic_string,
std::__1::allocator >, std::__1::basic_string, std::__1::allocator >)",
referenced from:
> _wrap_PETScObject_petsc_error(_object, _object) in modulePYTHON_wrap.cxx.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see
invocation)

**Comment by mikaem** [comment]
Ok, great, then I'll leave the recipe as it is for now.

**Comment by garth-wells** [comment]
Passing all test as of ebbd2993afaa675b0b9b32b0c60b685715f7f699.
