### ISSUE TITLE
after installing `fenics=2017.2`, `mumps-mpi` breaks other packages that depend on `mumps`

### ISSUE THREAD

**Issue by piskunow** [conda-forge/fenics-feedstock#62]
Installing `fenics=2017.2`, also installs `mumps-mpi`,
which makes my installation of `kwant=dev` stop working.

Another way is to install `fenics=2007.2`, and build `kwant`
from source. In this case, inside a python shell, if you `import kwant`
it warns about not having `mumps` installed. But if you
`import fenics; import kwant` then there is no issue.

Here a snippet to reproduce the bug.

Installing kwant from `kwant channel` and fenics from `conda-forge`
```
$ conda create -n test_fenics python=3.6 fenics=2017.2 kwant=dev
... after installing
$ conda activate test_fenics
$ python -c 'import kwant; print(hasattr(kwant.linalg, "mumps"))'
> True
$ python -c 'import fenics; import kwant'
> ** ERROR RETURN ** FROM ZMUMPS INFO(1)=   -3
> ** INFO(2)=        -1
(n times)
```

Building kwant from source, and installing fenics from `conda-forge` (continue with previous env)
```
$ conda uninstall kwant
$ conda install cython && pip install git+ssh://git@gitlab.kwant-project.org:443/kwant/kwant.git
$ python -c 'import kwant; print(hasattr(kwant.linalg, "mumps"))'
> RuntimeWarning: MUMPS is not available, SciPy built-in solver will be used as a fallback.
   Performance can be very poor in this case.
> False
$ python -c 'import fenics; import kwant'
>
```

**Comment by minrk** [comment]
This is an issue with how mumps and mumps-mpi are built, containing conflicting file names. It's open on the mumps feedstock [here](https://github.com/conda-forge/mumps-feedstock/issues/34), so I'll close this issue. It should be fixed by a new [mumps-seq](https://github.com/conda-forge/mumps-feedstock/issues/34) which doesn't collide with mumps-mpi.
