### ISSUE TITLE
FEniCS 2017.2.0 imcomptible with SymPy 1.2

### ISSUE THREAD

**Issue by Rfp94** [conda-forge/fenics-feedstock#66]
Issue:
Hi,
Fenics-JIT compiler is not compatible with latest version of SymPy. Could you fix the dependancies tree ?

https://www.allanswered.com/post/qwqwo/#rrxrr

Best regards,

<br/>

Environment (<code>conda list</code>):

# packages in environment at /home/myname/.conda/envs/FEniCS:
#
blas                      1.1                    openblas    conda-forge
boost                     1.66.0                   py27_1    conda-forge
boost-cpp                 1.66.0                        1    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2018.4.16                     0    conda-forge
certifi                   2018.4.16                py27_0    conda-forge
cloog                     0.18.0                        0  
cmake                     3.11.4                        0    conda-forge
curl                      7.60.0                        0    conda-forge
eigen                     3.3.3                         0    conda-forge
expat                     2.2.5                         0    conda-forge
fastcache                 1.0.2                    py27_0    conda-forge
fenics                    2017.2.0            np113py27_3    conda-forge
gcc                       4.8.5                         7  
gmp                       6.1.2                         0    conda-forge
gmpy2                     2.0.8                    py27_1    conda-forge
hdf5                      1.10.1                        2    conda-forge
hypre                     2.11.2                        1    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
isl                       0.12.2                        0  
krb5                      1.14.6                        0    conda-forge
libgcc                    5.2.0                         0  
libgcc-ng                 7.2.0                hdf63c60_3    anaconda
libgfortran               3.0.0                         1  
libgfortran-ng            7.2.0                hdf63c60_3    anaconda
libopenblas               0.2.20               h9ac9557_7    anaconda
libssh2                   1.8.0                         2    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3    anaconda
libuv                     1.20.3                        0    conda-forge
metis                     5.1.0                h470a237_3    conda-forge
mkl                       2017.0.3                      0  
mpc                       1.1.0                         4    conda-forge
mpfr                      3.1.5                         0    conda-forge
mpi                       1.0                       mpich    conda-forge
mpich                     3.2.1                h26a2512_4    conda-forge
mpmath                    1.0.0                      py_0    conda-forge
mumps-mpi                 5.0.2           blas_openblas_0  [blas_openblas]  conda-forge
ncurses                   5.9                          10    conda-forge
numpy                     1.13.3          py27_blas_openblas_201  [blas_openblas]  conda-forge
numpy-base                1.14.3           py27h0ea5e3f_1    anaconda
openblas                  0.2.20                        8    conda-forge
openssl                   1.0.2o                        0    conda-forge
parmetis                  4.0.3                hf0665dc_2    conda-forge
pcre                      8.41                          1    conda-forge
petsc                     3.8.4           blas_openblas_0  [blas_openblas]  conda-forge
petsc4py                  3.8.1                    py27_1    conda-forge
pip                       9.0.3                    py27_0    conda-forge
pkg-config                0.29.2                        1    conda-forge
ply                       3.11                       py_1    conda-forge
ptscotch                  6.0.4                         3    conda-forge
python                    2.7.15                        0    conda-forge
readline                  7.0                           0    conda-forge
rhash                     1.3.4                         0    conda-forge
scalapack                 2.0.2                h186ce0b_3    conda-forge
scotch                    6.0.5                h9c0d707_1    conda-forge
setuptools                40.0.0                   py27_0    conda-forge
six                       1.11.0                   py27_1    conda-forge
slepc                     3.8.3           blas_openblas_0  [blas_openblas]  conda-forge
slepc4py                  3.8.0                    py27_0    conda-forge
sqlite                    3.20.1                        2    conda-forge
subprocess32              3.2.7                    py27_0  
suitesparse               4.5.4           blas_openblas_201  [blas_openblas]  conda-forge
swig                      3.0.12                        2    conda-forge
sympy                     1.2                      py27_0    conda-forge
tbb                       2018_20171205                 0    conda-forge
tk                        8.6.7                         0    conda-forge
wheel                     0.31.1                   py27_0    conda-forge
xz                        5.2.3                         0    conda-forge
zlib                      1.2.11                        0    conda-forge

<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by minrk** [comment]
Thanks! Have you checked with fenics 2018.1, or is it just 2017.2 that needs this?

**Comment by Rfp94** [comment]
Sorry, I'm not able to tell you if the conflicts is solved with fenics 2018.1.

**Comment by sigvaldm** [comment]
This affects 2018.1 as well. As far as I can tell, this has been fixed for the next version (2018.2). See https://bitbucket.org/fenics-project/fiat/issues/27/sympy-12-breaks-diff-of-expression-without . Running `conda install sympy=1.1.1` on a fresh environment with this package installed fixed it for me.

**Comment by minrk** [comment]
Thanks! #67 pins sympy < 1.2 for 2018.1
