### ISSUE TITLE
MUMPS seems to be super slow on Ubuntu 18

### ISSUE THREAD

**Issue by z-hasher** [conda-forge/fenics-feedstock#77]
Not sure if this is the right place to ask. I modified the fenics hyperelastic demo to make it with 768k tets (80x80x20 intervals). 

On Ubuntu 18, I use Anaconda3 fenics package with MUMPS. Per Newton step, it took about 10 min per Newton step (one direct solve) whether or not MPI is used (when using MPI I used -np 8, the machine is with 8 cores 16 threads).

On my macbook with Anaconda fenics (same version: 2018.1.0), one Newton step took a minute or so, though parallel didn't help much either.

Not sure what's causing the difference.

Thanks

**Comment by minrk** [comment]
Can you share `conda list`?

**Comment by drew-parsons** [comment]
Sometimes unexpected slow MPI performance happens due to threads (effectively overloading the CPUs). For MPI jobs you might want to constrain to 1 thread per MPI process by setting
```
export OMP_NUM_THREADS=1
```

**Comment by jan-janssen** [comment]
This should be fixed now, otherwise feel free to open a new issue.
