### ISSUE TITLE
Add packages for python 3.8

### ISSUE THREAD

**Issue by thisch** [conda-forge/fenics-feedstock#97]
Issue:

It is not yet possible to install fenics in a python3.8 conda env.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by jbweston** [comment]
This is also preventing the `mshr` package from building for python3.8 (see [here](https://github.com/conda-forge/mshr-feedstock/pull/17))
