### ISSUE TITLE
Adapt version pinning of numpy

### ISSUE THREAD

**Issue by thisch** [conda-forge/fenics-feedstock#99]
fenics is using a different numpy version pinning compared to other projects from the scientific python stack, e.g., scipy/pandas/h5py

https://github.com/conda-forge/scipy-feedstock/pull/100/files
https://github.com/conda-forge/pandas-feedstock/pull/62/files
https://github.com/conda-forge/h5py-feedstock/blob/master/.ci_support/linux_mpiopenmpipython3.7.yaml

**The pinned version of numpy should be changed to 1.14.**

This will probably fix issues like:

```numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject```

in code that is built against a newer version of numpy.

**Comment by thisch** [comment]
@garth-wells @johannesring @mikaem @minrk  Do you have an opinion about this? Are you in principle in favor of pinning numpy to 1.14?

**Comment by minrk** [comment]
Do you have a test that shows this? It's a little surprising since those packages are built against 1.14 and should be compatible with any numpy >=1.14,<2.0, which includes 1.16. Only fenics pins numpy to a minor version, and thus appears to be compatible with the latest builds of all of those. Normally, when I install any of these packages, I get numpy 1.17, which doesn't seem to be an issue, and don't see this error when I try to use the packages together.

btw, I'm not opposed to unpinning it, since that pinning I believe was a relic of the swig code generation and should no longer be an issue since the switch to pybind11, but I don't understand how we are getting this issue.

**Comment by thisch** [comment]
Thx for your detailed answer. Yes we have tests that show this issue: We build some custom c extensions (those c-extensions are independent of our fenics code) against a newer version of numpy that is required by fenics. This leads to the 'incompatiblity' error msg from the description. We tried to pin the numpy lib to the same version as was used for building scipy/pandas/h5py.., but due to the version pinning of fenics this was not possible. 

I agree, if fenics doesn't link against numpy, you can completely unpin numpy, as you do in #100.

**Comment by minrk** [comment]
Thanks! Sorry for being unclear, but do you have a test to share here that I can run?

**Comment by thisch** [comment]
> Thanks! Sorry for being unclear, but do you have a test to share here that I can run?

No, we unfortunately don't have one that I can share.

**Comment by thisch** [comment]
Is it possible to download/install a CI built fenics package from an unmerged PR?

**Comment by minrk** [comment]
> Is it possible to download/install a CI built fenics package from an unmerged PR?

No, unfortunately not. You can build the linux version locally by checking out the branch and running `python build-locally.py linux_` and then installing the resulting packages.

**Comment by thisch** [comment]
I'm using podman as a container frontend instead of docker. I have a problem with the script, not sure if it is podman related or not:

```
.....
Executing transaction: ...working... done
+ setup_conda_rc /home/conda/feedstock_root /home/conda/recipe_root /home/conda/feedstock_root/.ci_support/linux_.yaml
+ source run_conda_forge_build_setup
++ export PYTHONUNBUFFERED=1
++ PYTHONUNBUFFERED=1
++ conda config --set show_channel_urls true
++ conda config --set auto_update_conda false
++ conda config --set add_pip_as_python_dependency false
++ export CONDA_BLD_PATH=/home/conda/feedstock_root/build_artifacts
++ CONDA_BLD_PATH=/home/conda/feedstock_root/build_artifacts
++ set +u
++ '[' '' = drone ']'
++ '[' '' = travis ']'
++ export CPU_COUNT=2
++ CPU_COUNT=2
++ '[' '!' -z linux_ ']'
++ echo ''
/opt/conda/bin/run_conda_forge_build_setup: line 23: /home/conda/feedstock_root/.ci_support/linux_.yaml: Permission denied
Traceback (most recent call last):
  File "build-locally.py", line 63, in <module>
    main()
  File "build-locally.py", line 59, in main
    run_docker_build(ns)
  File "build-locally.py", line 19, in run_docker_build
    subprocess.check_call([script])
  File "/home/thomas.hisch/miniconda/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['.scripts/run_docker_build.sh']' returned non-zero exit status 1.
```
